# 应用服务 WEB 访问端口
server.port=5200

########################MySQL数据库连接配置
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/myschool
spring.datasource.username=root
spring.datasource.password=root1234

########################MyBati配置
#指定Mybatis的Mapper文件
mybatis.mapper-locations=classpath:mapper/*xml
#指定Mybatis的日志信息输出到控制台
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
#指定Mybatis的实体目录
mybatis.type-aliases-package=com.bing.pojo

