# SpringBoot有三种配置文件，分别是：application.properties.bak、application.yml、application.yaml.bak
# 优先级是 properties > yml > yaml
# properties配置文件层级结构不够清晰，而且配置信息会大量冗余，所以推荐使用yml/yaml，这里我们使用yml
# 注意：yml 和 yaml在配置信息时，:后面要加空格，然后再写值，层级之间使用空格缩进

# 服务端口
server:
  port: 5200

# Spring配置
spring:
  datasource:   # MySQL数据库连接配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myschool
    username: root
    password: root1234
  servlet:      # servlet相关配置
    multipart:  # 配置文件上传
      max-file-size: 10MB  # 单个文件最大上传大小（默认值是1MB）
      max-request-size: 100MB  # 单次请求的最大上传大小（默认值是10MB）（一次请求可以上传多个文件）

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*xml  # 指定Mybatis的Mapper文件路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #指定Mybatis的日志信息输出到控制台
  type-aliases-package: com.bing.pojo  #指定Mybatis的实体类的包信息

# 阿里云OSS配置信息
aliyun:
  oss:
    bucketName: bing-3
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tKkBaEfpyJGZogSXgv5
    accessKeySecret: vSzWXh7T6BAf95tz0D8R5AdMXHxY5h



